In [1]:
import pandas as pd
import numpy as np

# Data wrangling

## changing created_at and last_move_at columns to datetime data type

In [2]:
chess = pd.read_csv('chess.csv')

df_times = chess[['created_at','last_move_at']].copy()

df_times['created_at_dt'] = pd.to_datetime(df_times['created_at']/1000, 
                                           unit='s', 
                                           origin='unix')

df_times['last_move_at_dt'] = pd.to_datetime(df_times['last_move_at']/1000, 
                                             unit='s', 
                                             origin='unix')

df_times.tail(6)

         created_at  last_move_at       created_at_dt     last_move_at_dt
20052  1.499810e+12  1.499810e+12 2017-07-11 21:53:20 2017-07-11 21:53:20
20053  1.499790e+12  1.499790e+12 2017-07-11 16:20:00 2017-07-11 16:20:00
20054  1.499700e+12  1.499700e+12 2017-07-10 15:20:00 2017-07-10 15:20:00
20055  1.499700e+12  1.499700e+12 2017-07-10 15:20:00 2017-07-10 15:20:00
20056  1.499700e+12  1.499700e+12 2017-07-10 15:20:00 2017-07-10 15:20:00
20057  1.499640e+12  1.499640e+12 2017-07-09 22:40:00 2017-07-09 22:40:00

## Merging new dataset with original dataset

In [3]:
chess1 = pd.concat([chess, df_times], axis=1)
chess1.head()

,id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply,created_at,last_move_at,created_at_dt,last_move_at_dt
0,TZJHLljE,False,1.500000e+12,1.500000e+12,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5,1.500000e+12,1.500000e+12,2017-07-14 02:40:00,2017-07-14 02:40:00
1,l1NXvwaE,True,1.500000e+12,1.500000e+12,16,resign,black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4,1.500000e+12,1.500000e+12,2017-07-14 02:40:00,2017-07-14 02:40:00
2,mIICvQHh,True,1.500000e+12,1.500000e+12,61,mate,white,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3,1.500000e+12,1.500000e+12,2017-07-14 02:40:00,2017-07-14 02:40:00
3,kWKvrqYL,True,1.500000e+12,1.500000e+12,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3,1.500000e+12,1.500000e+12,2017-07-14 02:40:00,2017-07-14 02:40:00
4,9tXo1AUZ,True,1.500000e+12,1.500000e+12,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5,1.500000e+12,1.500000e+12,2017-07-14 02:40:00,2017-07-14 02:40:00

## Dropping original created_at and last_move_at columns

In [4]:
chess1.drop(['created_at', 'last_move_at'], axis=1)

,id,rated,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply,created_at_dt,last_move_at_dt
0,TZJHLljE,False,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5,2017-07-14 02:40:00,2017-07-14 02:40:00
1,l1NXvwaE,True,16,resign,black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4,2017-07-14 02:40:00,2017-07-14 02:40:00
2,mIICvQHh,True,61,mate,white,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3,2017-07-14 02:40:00,2017-07-14 02:40:00
3,kWKvrqYL,True,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3,2017-07-14 02:40:00,2017-07-14 02:40:00
4,9tXo1AUZ,True,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5,2017-07-14 02:40:00,2017-07-14 02:40:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,EfqH7VVH,True,24,resign,white,10+10,belcolt,1691,jamboger,1220,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,Dutch Defense,2,2017-07-11 16:20:00,2017-07-11 16:20:00
20054,WSJDhbPl,True,82,mate,black,10+0,jamboger,1233,farrukhasomiddinov,1196,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,Queen's Pawn,2,2017-07-10 15:20:00,2017-07-10 15:20:00
20055,yrAas0Kj,True,35,mate,white,10+0,jamboger,1219,schaaksmurf3,1286,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,Queen's Pawn Game: Mason Attack,3,2017-07-10 15:20:00,2017-07-10 15:20:00
20056,b0v4tRyF,True,109,resign,white,10+0,marcodisogno,1360,jamboger,1227,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,B07,Pirc Defense,4,2017-07-10 15:20:00,2017-07-10 15:20:00
20057,N8G2JHGG,True,78,mate,black,10+0,jamboger,1235,ffbob,1339,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,Queen's Pawn Game: Mason Attack,3,2017-07-09 22:40:00,2017-07-09 22:40:00

## Checking data types

In [6]:
chess1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               20058 non-null  object
 1   rated            20058 non-null  bool
 2   created_at       20058 non-null  float64
 3   last_move_at     20058 non-null  float64
 4   turns            20058 non-null  int64
 5   victory_status   20058 non-null  object
 6   winner           20058 non-null  object
 7   increment_code   20058 non-null  object
 8   white_id         20058 non-null  object
 9   white_rating     20058 non-null  int64
 10  black_id         20058 non-null  object
 11  black_rating     20058 non-null  int64
 12  moves            20058 non-null  object
 13  opening_eco      20058 non-null  object
 14  opening_name     20058 non-null  object
 15  opening_ply      20058 non-null  int64
 16  created_at       20058 non-null  float64
 17  last_move_at     20058 non-null  float64
 18  created_at_dt    20058 non-null  datetime64[ns]
 19  last_move_at_dt  20058 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](2), float64(4), int64(4), object(9)
memory usage: 2.2+ MB